apiVersion: apps/v1 # for version before 1.9.0 use apps/v1beta2
kind: Deplyment
metadata: 
  name: jenkins #basically-micro-services-name
spec: 
  selector: 
    matchLabels:
      app: jenkins
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: jenkins
    spec: 
      containers: 
      - name: jenkins
        image: jenkins
        - containerPort: 8080
        
